export { default as About } from './about'
export { default as Cart } from './cart'
export { default as Checkout } from './checkout'
export { default as Error } from './error'
export { default as HomeLayout } from './homeLayout'
export { default as Landing } from './landing'
export { default as Orders } from './orders'
export { default as Products } from './products'
export { default as SingleProduct } from './singleProduct'
export {default as Login} from './login'
export {default as Register} from './register'